#!/bin/sh
export ENV_NAME=dev

echo "Deploying to kubernetes..."
envsubst < ./deploy/deployment.yaml | kubectl apply -f -

echo "Deploying to API Connect..."
apic config:set catalog=apic-catalog://us.apiconnect.ibmcloud.com/orgs/dingersjigsawxyz-fab-dev/catalogs/dev
apic login --username ${APIC_USERNAME} --password ${APIC_PASSWORD} --server us.apiconnect.ibmcloud.com
apic publish --catalog dev --organization dingersjigsawxyz-fab-dev --server us.apiconnect.ibmcloud.com definitions/*-product.yaml
