#!/bin/sh
export ENV_NAME=dev

echo "Deploying to kubernetes..."
envsubst < ./deploy/deployment.yaml | kubectl apply -f -

echo "Deploying to API Connect..."
apic config:set catalog=apic-catalog://us.apiconnect.ibmcloud.com/orgs/dingersjigsawxyz-fab-dev/catalogs/dev
apic login --username ${APIC_USERNAME} --password ${APIC_PASSWORD} --server us.apiconnect.ibmcloud.com
apic publish --catalog dev --organization dingersjigsawxyz-fab-dev --server us.apiconnect.ibmcloud.com definitions/*-product.yaml

echo "Getting Object Storage access key"
TOKEN=`curl -X "POST" "https://iam.bluemix.net/oidc/token" \
     -H 'Accept: application/json' \
     -H 'Content-Type: application/x-www-form-urlencoded' \
     --data-urlencode "apikey=bkq8-t8QZhRwtw31MggGqnoXFScgyh2MZDvzKKJACjAu" \
     --data-urlencode "response_type=cloud_iam" \
     --data-urlencode "grant_type=urn:ibm:params:oauth:grant-type:apikey" \
     | jq -r '.access_token'`

echo "Saving API swagger files to Object Storage"
FILES=`ls -1 -F definitions/`
for FILENAME in ${FILES}
do
  IFS='.'
  API=($FILENAME)
  unset IFS
  TARGET_FILENAME=${API[0]}-${CI_COMMIT_TAG}.yaml
  echo "Saving https://s3-api.us-geo.objectstorage.softlayer.net/fab-apic-definitions/${TARGET_FILENAME}"

  curl -X "PUT" "https://s3-api.us-geo.objectstorage.softlayer.net/fab-apic-definitions/${TARGET_FILENAME}" \
         -H "Authorization: Bearer ${TOKEN}" \
         -H "Content-Type: text/plain; charset=utf-8" \
         --data-binary "@definitions/${FILENAME}"
done
